### ISSUE TITLE
Not flashing

### ISSUE THREAD

**Issue by SeriousSeri** [AndersonLeandrog/RunTWRP#1]
Hey there =)

I tried to flash 3.5.2_9 on my Moto G5s Plus (Sanders)
Did all the usual stuff (TWRP 3.5.1_9 is already installed) as stated in your description. The Console even gives me an everything successful message, but unfortunately the Version Number is still showing 3.5.1_9

I know, thats little to no help to narrow it down, but i don't know what to tell you atm besides "it does not work" ^^

Greetings and thanks for the effort =)

**Comment by AndersonLeandrog** [comment]
> Hey there =)
> 
> I tried to flash 3.5.2_9 on my Moto G5s Plus (Sanders)
> Did all the usual stuff (TWRP 3.5.1_9 is already installed) as stated in your description. The Console even gives me an everything successful message, but unfortunately the Version Number is still showing 3.5.1_9
> 
> I know, thats little to no help to narrow it down, but i don't know what to tell you atm besides "it does not work" ^^
> 
> Greetings and thanks for the effort =)

**Hello,** _thanks for reporting this problem, I made some changes in the program and tested it on my G5s Plus device, you can test it now, if the error persists check the connection with the USB cable between your device and PC, if possible try with another data cable ; )_

**I've got an external link to the G5s Plus twrp 3.5.2-9 file**

**Comment by SeriousSeri** [comment]
In the meantime i just installed it manually, USB connection was working fine, Charging and File Transfer did at least, so i am assuming =) But glad you could solve this! And thanks again, for the next TWRP update i will surely come back for another try! Especially on phones which do not have TWRP installed, because that's where this is really convenient for, aye ;)
