### ISSUE TITLE
Cannot execute

### ISSUE THREAD

**Issue by AnselRS** [AndersonLeandrog/RunTWRP#2]
Hi Leandro,

Something is wrong when executing your code:

**The program can't start because libgcc_s_dw2-1.dll is missing from your computer.
Try reinstalling the program to fix this problem.

The program can't start because libstdc++-6.dll is missing from your computer.
Try reinstalling the program to fix this problem.**

Your video on youtube shows a list of files different from that on github!
https://www.youtube.com/watch?v=ZcSJQMfkcNk

For instance, there is no autorun, README files nor those libs... in the zip file!

As a newbie I would like to use your solution but it crashed on me...

Could you review that?  I would like to try again.

Regards
Anselmo
Rio de Janeiro

**Comment by AnselRS** [comment]
BTW: 
Edition	Windows 10 Pro
Version	20H2
OS build	19042.1052

**Comment by AndersonLeandrog** [comment]
Hello @AnselRS, yes the program is a little different from the one seen in the video, this is because it has been modified but it still has its functionality.

Try to run the latest version so far which is 1.4.9 just released, in previous versions the program needed the aforementioned dll's so it could run, but in current versions, from 3.0.0 + onwards there is no longer the need for these dll's as they are already included when the program is compiled.


Method 1. If your problem is still not resolved then download dlls [fixDLL](https://github.com/AndersonLeandrog/Android-UTools/tree/main/fixDLLS) download the two dlls and move them to the root of the program, this will make the program run normally without errors.

Method 2. Probably your computer does not have this dll, another way would be to install this dll in your computer, usually in C:/Windows/System32/here-your.dll but try the first method before running this second one.

@AndersonLeandrog

**Comment by AndersonLeandrog** [comment]
This program uses the MinGW compiler, so it needs the dll's it already provides included in the compiler, although these dll's are not necessarily MinGW's own, this is, they are not only used in the compiler, so generally they are also included in windows.

**Comment by AnselRS** [comment]
Opa Anderson,

Congratulations on your work with this project!

This time, I could run your AndroidUserTools but only after downloading and adding your dlls to the same program folder.
I don´t think those dlls would be missing on an regular Windows 10.
Maybe they exist in your specific ambient as you have your compiler installed.

Anyway, all that is because my device (Moto G5Splus) is stuck in a BootLoop and to worsen things, with a LockedBootloader and USBdebuging_NOT_Enabled!

All I can do is to boot into bootloader and fastboot but cannot use ADB from my computer:
It seems adb requires usb debuging to be enabled (and maybe an unlocked bootloader)... As far as I have seen, I can´t do this now on a device that does not boot into Android  (bootloop)...

From Windows:
>adb devices
List of devices attached
[empty]

>fastboot devices
0039679nnn      fastboot    <<< my device!

From AndroidUserTools:
-----------------------------------
 [1] TWRP Install

REQUIREMENTS FOR INSTALATION

 * ADB and Fastboot drivers, visit: https://adb.clockworkmod.com/
 * Drivers of your mobile device (look for the driver for your device model)
 * Unlocked bootloader (see the video on how to unlock on my youtube channel)

A duplicate file name exists, or the file
cannot be found.
< waiting for device >
....  nothing happens
-----------------------------------

Obs:
ADB/Fastboot from https://developer.android.com
Drives of device from Motorola/Lenovo

I know I should do a factory reset, but "of course" I didn´t make a recent backup of my data... "dei mancada mesmo..."

That is why I am trying your tool just to see if it could do anything different in this difficult context.
As far as I can tell, your AndroidUserTools would be very usefull to me just if my phone had the bootloader unlocked and USB debug enabled...
I´ve read that unlocking the bootloader would wipe data, clearing all user files (Moto G5Splus)!  Any workaround here?

By the way, would you have any other clue or path that could avoid data loss in this situation?
Anything that could allow a last data recovery before a factory reset?  I can keep this phone this way for a while and try any other possible solution.
Eventually, I pretend to try to install another ROM on it. Maybe LineageOS... any thoughts?

Finally and again, congratulations! Keep this good job!

Valeu!

-----------
Regards,
Anselmo
Rio de Janeiro

**Comment by AndersonLeandrog** [comment]
Good morning @AnselRS, the program uses some ADB commands and this in turn unfortunately requires you to have the bootloader unlocked and USB debugging enabled for some procedures, for example to install TWRP you need to have at least the bootloader unlocked .

And no, you don't lose any data if you unlock the bootloader, I don't know who advised you on this, but this person was wrong, the bootloader unlocking process doesn't require any formatting.

It will just say unlock a code inside your device, nothing more. It doesn't directly mess with your files.

Try to unlock your device's bootloader and then install TWRP using the tool, after installing TWRP you will have two options:

1. Install a custom system of your liking and after starting the system you can enable adb by android itself.

2. Enable ADB via TWRP, this is possible in most current versions of TWRP.

**Comment by AndersonLeandrog** [comment]
If you can send me any images, please don't hesitate, it's a bit difficult to know what's really going on and return useful feedback without the images.

**Comment by AnselRS** [comment]
Hi Leandro,

Thank you for your guidance!

I really read that unlocking the bootloader would clear data...  It was at Lenovo's/Motorola's site (first item) link below:

https://motorola-global-portal.custhelp.com/app/standalone/bootloader/unlock-your-device-a

If you have a different experience from your practice and, if you can, please confirm your affirmation so I would take this step (under my sole responsibility) and then try TWRP and a recovery.

Thank you again!

Anselmo
Rio de Janeiro.

**Comment by AndersonLeandrog** [comment]
Although this is reported on the motorola website I think this occurs in rare cases, but of all the motorola devices that I have worked on I have not lost any data just with the bootloader unlock process, unless you unlock the bootloader and then format your device (which is not a requirement).

I understand that you don't want to lose your data, in which case you can simply move all of them to a pendrive if your device is still being recognized through fastboot by your computer.

Since you are unable to access the system, that is, you are stuck in the recovery screen, the only way I can see how to recover your device and the data inside it is to make a backup by computer, in case this backup is not possible. , sorry to inform you, but the only way is to remove your data.

**Comment by AndersonLeandrog** [comment]
There is one last way for you to recover your files, it consists of 1. unlocking your bootloader, 2. Installing TWRP on your device, 3. Opening TWRP and connecting your device to the PC, maybe this way your device be recognized by the computer and finally you can recover your data and after that install a ROM (I recommend you install a stock first) if everything works out, go back and install a custom rom.

**Comment by AnselRS** [comment]
Hi Leandro,

Thank you for your clarification.

I will proceed to unlock the bootloader.

Now I'm just trying to get my unlocking code from the Motorola's support site, which by the way, won't recognize my Lenovo's username.   I'll create a new one in the support site.

I'll keep you informed when and how this all finally ends...

Regards,
Anselmo.

**Comment by AnselRS** [comment]
Hi Leandro,

I think I´m really locked as another flag should be set by Android but I can´t even boot the SO:
"Allow OEM Unlock"

Look what happened when I tryed to unlock th bootloader:
>fastboot oem unlock nnnnnnnnnnnnnnnn
(bootloader) Check 'Allow OEM Unlock' in Android Settings > Developer Options
OKAY [  0.000s]
Finished. Total time: 0.000s

I think I´ll have to do a factory reboot anyway...

Regards
Anselmo

**Comment by AndersonLeandrog** [comment]
Did you try to unlock it through the program? if yes, you tried to do it normally without the program, it returns the same error?

**Comment by AndersonLeandrog** [comment]
Of course the problem in this case is that bootloader unlocking on your device is not enabled there in your device settings, under Settings > Developer mode > OEM Unlock -

Well in this case I don't know any method that can enable the OEM without properly entering the system.

I can recommend you a group on the telegram in which I participate, we exchanged some experiences through the group, it is exclusively focused on the Moto G5 line (All variants).

https://t.me/BRSanders

**Comment by AnselRS** [comment]
Hi Leandro,

I finally gave up on trying to recover my files.    A factory reset and my
device returned to "life"...

My lessons:

Before needed:

- Enable option to unlock bootloader (Allow OEM unlock) on Android;

- Enable USB debugging on Android;

- And the obvious: keep clowd backups enabled or do home backups frequently.

Anyway, thank you very much for your support.  I wish you big success with
your projects.

--------
Anselmo
Rio de Janeiro

On Aug 10, 2021 7:19 PM, "Anderson Leandro" ***@***.***>
wrote:

Of course the problem in this case is that bootloader unlocking on your
device is not enabled there in your device settings, under Settings >
Developer mode > OEM Unlock -

Well in this case I don't know any method that can enable the OEM without
properly entering the system.

I can recommend you a group on the telegram in which I participate, we
exchanged some experiences through the group, it is exclusively focused on
the Moto G5 line (All variants).

https://t.me/BRSanders

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/AndersonLeandrog/Android-UTools/issues/2#issuecomment-896349768>,
or unsubscribe
